export const Permissions = {
    // Routes
    ROUTE_CREATE: "ROUTE_CREATE",
    ROUTE_EDIT_ANY: "ROUTE_EDIT_ANY",
    ROUTE_EDIT_OWN: "ROUTE_EDIT_OWN",
    ROUTE_DELETE_ANY: "ROUTE_DELETE_ANY",
    ROUTE_DELETE_OWN: "ROUTE_DELETE_OWN",
    ROUTE_UPLOAD_GPX_OWN: "ROUTE_UPLOAD_GPX_OWN",

    // Businesses
    BUSINESS_CREATE: "BUSINESS_CREATE",
    BUSINESS_EDIT_ANY: "BUSINESS_EDIT_ANY",
    BUSINESS_DISABLE_ANY: "BUSINESS_DISABLE_ANY",
    BUSINESS_APPROVE_ANY: "BUSINESS_APPROVE_ANY",

    // Offers
    OFFER_CREATE_OWN_BUSINESS: "OFFER_CREATE_OWN_BUSINESS",
    OFFER_EDIT_OWN_BUSINESS: "OFFER_EDIT_OWN_BUSINESS",
    OFFER_DISABLE_ANY: "OFFER_DISABLE_ANY",
    OFFER_DISABLE_OWN_BUSINESS: "OFFER_DISABLE_OWN_BUSINESS",
};
