"""add_address_to_business

Revision ID: 7d3bb3c59923
Revises: 0007
Create Date: 2026-01-20 14:53:12.361973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d3bb3c59923'
down_revision: Union[str, None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('athlete_profiles', 'display_name')
    op.add_column('businesses', sa.Column('address', sa.String(length=300), nullable=True))
    op.alter_column('businesses', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('routes', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=320),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=320),
               existing_nullable=False)
    op.alter_column('routes', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('businesses', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('businesses', 'address')
    op.add_column('athlete_profiles', sa.Column('display_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
