"""add_offer_price_and_tickets

Revision ID: c6e6e2daaff9
Revises: 0009
Create Date: 2026-01-27 15:44:06.945895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6e6e2daaff9'
down_revision: Union[str, None] = '0009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('validation_code', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'USED', 'EXPIRED', name='ticket_status'), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('validation_code')
    )
    op.create_index(op.f('ix_tickets_offer_id'), 'tickets', ['offer_id'], unique=False)
    op.create_index(op.f('ix_tickets_user_id'), 'tickets', ['user_id'], unique=False)
    
    # 1. Add columns as nullable first
    op.add_column('offers', sa.Column('vac_price', sa.Integer(), nullable=True))
    op.add_column('offers', sa.Column('stock_quantity', sa.Integer(), nullable=True))
    
    # 2. Set default values for existing rows
    op.execute("UPDATE offers SET vac_price = 500 WHERE vac_price IS NULL")
    op.execute("UPDATE offers SET stock_quantity = 10 WHERE stock_quantity IS NULL")
    
    # 3. Alter columns to be NOT NULL
    op.alter_column('offers', 'vac_price', nullable=False)
    op.alter_column('offers', 'stock_quantity', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'stock_quantity')
    op.drop_column('offers', 'vac_price')
    op.drop_index(op.f('ix_tickets_user_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_offer_id'), table_name='tickets')
    op.drop_table('tickets')
    # ### end Alembic commands ###
