"""add_business_logo_and_offer_image

Revision ID: e6dcfb93b900
Revises: c6e6e2daaff9
Create Date: 2026-02-03 15:59:47.266772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6dcfb93b900'
down_revision: Union[str, None] = 'c6e6e2daaff9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.add_column('offers', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'image_url')
    op.drop_column('businesses', 'logo_url')
    # ### end Alembic commands ###
